### ISSUE TITLE
Contact Roland for a 5th task

### ISSUE THREAD

**Issue by simi48** [NervzZ/Designing-learning-tools-project#16]

**Comment by simi48** [comment]
The points:
1. We're 5 people in the group and there are 4 points to be done by one team-member
2. Is it gonna be combined in the end or everyone submits his own or what the idea is (do we print it and everyone fills it out or we make a new google docs or just generally what the hell were supposed to do with it

**Comment by NervzZ** [comment]
Waiting on his answer
