### ISSUE TITLE
Finding similar educational games

### ISSUE THREAD

**Issue by NervzZ** [NervzZ/Designing-learning-tools-project#4]

**Comment by NervzZ** [comment]
Kerbal Space Program - Much bigger budget game than what we are aiming for but super interesting way to teach players about physics and astrophysics in a fun way (consequences included, good use of humor).

**Comment by NervzZ** [comment]
Cities Skylines - Much like Kerbal Space Program it gives quite a lot of space for the player to do mistakes that will manifest quite convincingly in according consequences which is arguably great to learn from experience.

**Comment by NervzZ** [comment]
Reader Rabbit - https://en.wikipedia.org/wiki/Reader_Rabbit
It's an old game franchise that was definitely meant to a very young audience but the techniques used to captivate attention and teach can definitely be adapted for teenagers to even adult. It has this "Dora the Explorer" aproach of teaching but in a more interactive way where the player feels like the game (or more precisely, characters) act like your teachers.

**Comment by lipefree** [comment]
[Quandary](https://www.quandarygame.org/#:~:text=Quandary%20engages%20students%20in%20ethical,engaging%20story%20and%20fun%20gameplay.)

'Quandary engages students in ethical decision-making and develops skills that help them identify and resolve ethical issues in their own lives through engaging story and fun gameplay. There is no one right answer in the game, just as in real life. But each action has consequences that affect the player, others in the community and the planet Braxos.'
