### ISSUE TITLE
Prompt text not displaying well

### ISSUE THREAD

**Issue by NervzZ** [NervzZ/Designing-learning-tools-project#71]
The text seems (after a line return?) to have a weird offset right now on certain parts of the prompt.

**Comment by simi48** [comment]
Not sure if related or should be a different issue, 
but in the lab level, prompts are hidden behind the scene:


![Image](https://github.com/NervzZ/Designing-learning-tools-project/assets/41296975/a4982e52-f71f-4c66-bcc2-d375d932c452)
